from k_atlas.live_onboarding.client_onboarding import generate_client_onboarding
from k_atlas.live_onboarding.readiness_matrix import build_readiness_matrix
from k_atlas.live_onboarding.platform_registry import list_platforms
